### ISSUE TITLE
IMAP服务器QTGate通讯评分完成后下一步是什么操作？

### ISSUE THREAD

**Issue by zwzk4** [QTGate/QTGate-Desktop-Client#1]
本机QTGate版本：v0.8.80，密钥页面绿色开锁标志，Email账户IMAP服务器QTGate通讯评分完成，接下去应该做什么？没有任何提示呀，还是已经可以设置代理了，本地端口在哪里？

**Comment by CoNETProject** [comment]
您好，
如果您是首次使用，在生成秘匙以後，填入IMAP帳戶，經過客戶端檢測成功後：
1）會出現發送請求QTGate進行對接的email警告框，在您同意後您的客戶端，會把IMAP帳戶信息發送Email到QTGate系統。
![1](https://user-images.githubusercontent.com/19976150/32472918-d14483e6-c319-11e7-9f4f-5762642a1260.jpg)
![2](https://user-images.githubusercontent.com/19976150/32472924-d9dd6176-c319-11e7-8e16-bbf9acb5451e.jpg)
2）QTGate系統在收到IMAP帳戶信息後，會試圖連結您的IMAP帳戶，然後您的客戶端也會連結IMAP帳戶，這樣就建立了QTGate系統的對接，然後需要在您的秘匙郵箱中，尋找QTGate發送的激活郵件，來激活您的秘匙：
![3](https://user-images.githubusercontent.com/19976150/32472960-f940f690-c319-11e7-8934-1f3bf62e1d3b.jpg)
![4](https://user-images.githubusercontent.com/19976150/32472966-0495d2a4-c31a-11e7-8a84-3efa85dd20ed.jpeg)
![5](https://user-images.githubusercontent.com/19976150/32472982-18ab661e-c31a-11e7-9c7c-b4604886fde1.jpeg)
3）您的秘匙被激活後，您和QTGate系統建立了秘密聯繫通道，在接下去的畫面您可以看到目前可以使用的代理服務區域。
![6](https://user-images.githubusercontent.com/19976150/32473048-68b9a88c-c31a-11e7-91d4-62ffddd2f877.jpeg)

**Comment by zwzk4** [comment]
使用GMX邮箱只能出现第一张图（没有标星），到不了第二张图.
outlook邮箱可以到第三张图但数分钟后跳出黑色窗口报错，只有一个退出QTgate的按钮。
我没有iCloud邮箱，因没有apple设备也无法注册

**Comment by CoNETProject** [comment]
我已經推特私信給您，我個人空餘未使用的iCLoud帳戶。

**Comment by CoNETProject** [comment]
Outlook邮箱作為註冊郵箱，在Outlook的郵箱中的QTGate激活郵件不能夠正常表示OpenPGP message格式，導致客戶黏貼後點擊【激活】按鈕長時間沒有反應，這個BUG已經找到，我們會盡快釋放修正版修正Outlook邮箱作為註冊郵箱不能夠激活的BUG。

**Comment by CoNETProject** [comment]
v0.8.81 fixed.

**Comment by Buccaneer01** [comment]
临时邮箱用的GMX，设置后一直是正在尝试连接email服务器

**Comment by CoNETProject** [comment]
這是這版本的一個Bug, 您可以嘗試右鍵點擊右下部Q梯圖標，在菜單裡選擇exit，完全退出客戶端，再次打開客戶端試一下。

**Comment by Buccaneer01** [comment]
退出，重新打开客户端很多次了，还是不行。而且“正在尝试连接email服务器”的状态，如果一直等待，最终会提示程序崩溃，导致整个系统断网，退出客户端后网络恢复正常。
看你们说用icloud的邮箱好，可是我没有苹果手机，也没有其他ios设备，貌似连@icloud的邮箱都注册不了，更不用说什么二次验证，应用密码了

**Comment by Buccaneer01** [comment]
现在又是这个提示，win10的防火墙私人，公用网络都允许通信了

Email伺服器的指定連接埠連結失敗，請檢查您的IMAP連接埠設定，如果您在一個防火牆內部，則有可能該端口被防火牆所屏蔽，您可以嘗試使用該IMAP伺服器的其他連接埠！

**Comment by impig33** [comment]
我已经连上QTGate服务器了，显示本地的的代理端口是3001，并且选的是"服务中"，我电脑的ip是192.168.1.100，我telnet 127.0.0.1 3001和telnet 192.168.1.100 3001都不通。

QTGate客户没有监听端口?

@QTGate 

.

**Comment by pronouncing** [comment]
使用了iCloud臨時帳戶;

已向QTGate系统发送连接请求Email。由于是首次连接QTGate系统，系统需要几分钟时间来完成与您的对接，请耐心等待。 

错误
未能够与QTGate服务器对接成功。 QTGate系统可能存在问题，请稍後再次尝试。或联系QTGate服务。

就是连接不上是什么问题....
