### ISSUE TITLE
连不上了，是否被墙了?

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [QTGate/QTGate-Desktop-Client#11]
![_20180303132032](https://user-images.githubusercontent.com/12248166/36930909-39626134-1ea3-11e8-9bf2-bd61b3b199fd.png)

年前可以用，今天不行了

**Comment by CoNETProject** [comment]
不存在被牆一說，因為我們是使用郵箱溝通的，除非電子郵件無法使用。您可以嘗試下載我們最新版，更新您的QTGate試一下。

**Comment by piiiiiiiiiiiiiii** [comment]
已经是1.2.7

**Comment by CoNETProject** [comment]
那您嘗試一下完全退出QTGate，再次打開一下。

**Comment by CoNETProject** [comment]
我們服務器剛才收到了您的郵件，看上去是您的證書有問題。您看來需要重新生成證書。在打開QTGate，輸入密碼的地方刪除您的證書，重新生成新的證書，再次設定您的IMAP帳號。

**Comment by piiiiiiiiiiiiiii** [comment]
是的，我换了个电脑qtgate软件重装安装过了，填入账号这里新生成了密钥，但是服务器端存的应该还是旧的密钥，怎么更新过去呢? @QTGate

**Comment by CoNETProject** [comment]
您如果生成了新的秘匙，服務器會以您的新秘匙來覆蓋您的舊秘匙。這點不用擔心。

**Comment by piiiiiiiiiiiiiii** [comment]
`email伺服器IMAP連接成功
IMAP服务器QTGate通讯评分：`

那我的操作是对的，通信邮箱验证过后，连接qtgate连不上，就是上图中的样子。

**Comment by CoNETProject** [comment]
您的故障我們再現並確認了。這是我們服務器更新後產生的問題。我們正在解決之中。感謝您的報告。

**Comment by CoNETProject** [comment]
服務器故障已經排除。

**Comment by piiiiiiiiiiiiiii** [comment]
我验证之后再回复，谢谢 @QTGate

**Comment by piiiiiiiiiiiiiii** [comment]
这个问题解决了，原因是通信邮箱出问题了。

由于我平常是中国ip登录，qt服务器是国外的ip，两边ip都登录被outlook认为是邮箱被盗号了，限制了通信。

不过新问题来了:
1.27不会自动设置全局代理
https://github.com/QTGate/QTGate-Desktop-Client/issues/13
