### ISSUE TITLE
windows xp用哪个版本?

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [QTGate/QTGate-Desktop-Client#12]
我有一台xp 32的笔记本，分别下载了:

https://github.com/QTGate/QTGate-Desktop-Client/releases/download/v1.2.7/qtgate.Setup.1.2.7.ia32.exe
https://github.com/QTGate/QTGate-Desktop-Client/releases/download/v1.2.7/qtgate.Setup.1.2.7.exe

都提示不是有效的win32程序。
不支持xp了?

补充：
我之前提过这个问题，目前还不支持xp，请关贴，谢谢。
.

**Comment by CoNETProject** [comment]
今後我們會推出NodeJS版本來支持WindowsXP。如果您有NodeJS的操作經驗，您可以安裝NodeJS後，使用QTG。

**Comment by piiiiiiiiiiiiiii** [comment]
装好nodejs环境后，怎样使用qt呢?

**Comment by CoNETProject** [comment]
QTG目前還沒有在NodeJS上NPM項目，我們今後會推出QTG for NPM庫，您安裝完NodeJS後，可以通過NPM命令來獲取QTG執行程序。
