### ISSUE TITLE
【卡住】在尝试连接email服务器

### ISSUE THREAD

**Issue by An0nymous0** [QTGate/QTGate-Desktop-Client#15]
一直卡在在尝试连接email服务器

**Comment by CoNETProject** [comment]
您可否先使用我們提供的iCloud帳號試一下。

**Comment by CoNETProject** [comment]
在使用QTG的過程中請關閉VPN連結。

**Comment by An0nymous0** [comment]
google帐号不好使。测试的iCloud帐号可以，但是连接总断，动不动就不能上google了非常频繁。

**Comment by CoNETProject** [comment]
Gmail帳號如果您在國內的話，需要翻牆才能夠使用。而使用QTG的前提是不需翻牆就能夠使用。所以您不能使用Gmail帳號來使用QTG。您使用测试iCloud帐号已經和QTG連結上了，然後在使用Q梯時您連結總是斷下，那是由於您目前可能是免費帳號，您的本月流量已達限額。

**Comment by An0nymous0** [comment]
如果免费的流量用光了怎么办？ 是否有价格表？

**Comment by CoNETProject** [comment]
- 秘匙管理窗口

<img width="850" alt="122222" src="https://user-images.githubusercontent.com/19976150/37511770-4c535996-28bd-11e8-8832-bda417b01da4.png">
- 帳戶選項
<img width="850" alt="122223" src="https://user-images.githubusercontent.com/19976150/37511788-56ae72c2-28bd-11e8-84db-c58c29bd42b9.png">
- 選擇您的訂閱
<img width="850" alt="122224" src="https://user-images.githubusercontent.com/19976150/37511725-1f958104-28bd-11e8-8365-d871b46fdde6.png">
