### ISSUE TITLE
如何升级软件客户端

### ISSUE THREAD

**Issue by zzwxrchi** [QTGate/QTGate-Desktop-Client#16]
非常感谢你们的创新 !!
我在试用你们的软件, 但是有一些疑问.

怎么样升级, 比如 1.2.1 -> 1.3.4 ?
Ubuntu 16.40
我已经下载新版, 直接安装后, 客户端显示已经是新版, 但是连接时只能到30%, 老版可以到 100 %.
需要先卸载老版本再安装新版吗 ?
如何卸载 ?
如何确定我已经可以翻墙 (老版 @OPN 连接后外网 ip 似乎没有变化) ? 目前还未回国.

谢谢.

**Comment by CoNETProject** [comment]
您好，

在Windows和Mac版本之中，我們的軟件會自動檢測是否有最新版本，如果有最新版本，會自動下載，下載完成後會出現新版本已經準備好，是否現在升級的提示。
但是這項功能在Linux版本下不能夠使用，您需要手動檢查。今後我們會針對Linux版本進行特別的處理，幫助使用者簡單獲得更新。
您目前可以直接下載新版本安裝，應該不需卸載舊版本。
如果您需要卸載，您可以參照其他軟件卸載辦法，來完成我們的客戶端的卸載。

我們的客戶端，在連結代理服務器後，在您安裝的電腦上會提供一個本地代理服務器。這個時候您的其他任何設備包括手機，此Linux系統，都可以通過設定網絡使用這台本地代理服務器，來使用CoNET。

手機和其他系統的網絡代理設定，在客戶端連結後的窗口下方，有各個系統設定代理服務器的圖標，您可以點擊打開獲得幫助。

如何檢查您的代理服務器設定完成，您可以打開這個檢查網速的網站，它會顯示您當前的對外使用的IP地址，您比對一下連結前您的IP地址，和連結後您的IP地址是否發生了變化。

http://www.speedtest.net/

感謝您使用我們的服務。
