### ISSUE TITLE
显示QTGate已连接，但最后一步验证激活码一直转圈

### ISSUE THREAD

**Issue by miroku365** [QTGate/QTGate-Desktop-Client#17]
QTGate已连接，但最后一步验证激活码一直转圈，怎么办？用的outlook.com的邮箱

**Comment by CoNETProject** [comment]
這是當前版本的一個Bug.麻煩您嚐試完全退出程序，再次打開可以完成設定。

**Comment by miroku365** [comment]
完全退出程序，再打开，还是不行，一直转圈。- -!而且outlook收信的时候，总是会把激活码以附件形式收到“已发送”里面。
