### ISSUE TITLE
@opn can't connect

### ISSUE THREAD

**Issue by paul726** [QTGate/QTGate-Desktop-Client#18]
![qq 20180413105638](https://user-images.githubusercontent.com/9968970/38714586-8dbaa012-3f09-11e8-8cc5-73a728bf8f07.png)

**Comment by paul726** [comment]
[systemError.log](https://github.com/QTGate/QTGate-Desktop-Client/files/1905751/systemError.log)

**Comment by CoNETProject** [comment]
Hi paul726，

您好，您的Bug已經收到，感謝您的報告。
這是我們的代理服務器系統一個Bug，這個Bug有待我們服務器端的更新。
目前的解決方案是您可以嘗試選擇其他區域進行代理服務器的訂製。

**Comment by CoNETProject** [comment]
Fixed.
