### ISSUE TITLE
OutLook無法驗證

### ISSUE THREAD

**Issue by GW000001** [QTGate/QTGate-Desktop-Client#22]
使用OutLook郵箱接受code後paste驗證報錯目前使用最新版本QTGate仍無用其他郵箱無法連結

**Comment by CoNETProject** [comment]
謝謝您的報告，這是一個Bug. 將在下一個版本被修復。

**Comment by winnoryder** [comment]
原来如此啊，我今天折腾了半天时间，还以为是自己操作的问题
感谢作者的软件啊，身在大陆的民众非常需要，感谢

**Comment by CoNETProject** [comment]
謝謝您的支持。互聯網從發明的第一天起，就應該是自由無疆界的存在。但是目前被分割成一個個區域網，這是我們技術者們的悲哀。我們希望我們的項目能夠拋磚引玉，讓更多的支持互聯網自由的項目脫穎而出，在這場貓捉老鼠的遊戲中，支持互聯網自由的技術者們能夠勝出。

**Comment by CoNETProject** [comment]
您可以使用任何郵箱進行註冊，Outlook得網頁版本，在收到RSA加密的郵件後，郵件格式遭到破壞，需要對加密郵件重新整理後，才能夠解密使用。這個補丁我們已經完成，大概明後天會跟隨新的推特客戶端的Bate版，一起更新。

**Comment by CoNETProject** [comment]
如果您等不及新版本，您可以在寫字板里對收到的RSA信件自行修補：
錯誤的格式：

-----BEGIN PGP MESSAGE----- hF4DmdGogBHt6UUSAQdA/e/ZbseEJ7jSCDSztShIlaJr5ojkuIvcJOYwaCIXdhYw YkIPJG3Sv+yg/LBV75C4ByqgQXJx2zDLPTjffHRv8Ru0WV8CN4IOFbC0P6VVfzvV 0sAdAUT6HTB2my6YJpy3T3Poo06hK+cg23WQUzZwEc3BBIuusc5kQGztmAYmmK8H REQp5p1WDyp8LnkaYoRIwAqOTxJ7rlTUz/o12+Oy7VT6POn9wRu0xnwpUCfUkDeB R4U0cBfm29COO0asoldEA7dKU37syHNnZjzwgw8rR7gKpwVOoO0ldnqoIZ+PTkch zIbzvQIjKUVxTnr42mdxJWB1PO7EaJf6eo1+HeylfCjPRmXlIzJLpRnRC/PI3IWE NJG8sKgdlIIogL2rZQxRuFzXFBTlcJw1OARW6cid8to= =tCF2 -----END PGP MESSAGE----- 

修正以後的格式：在空格處把空格替換成回車
```
-----BEGIN PGP MESSAGE-----

hF4DmdGogBHt6UUSAQdA/e/ZbseEJ7jSCDSztShIlaJr5ojkuIvcJOYwaCIXdhYw
YkIPJG3Sv+yg/LBV75C4ByqgQXJx2zDLPTjffHRv8Ru0WV8CN4IOFbC0P6VVfzvV
0sAdAUT6HTB2my6YJpy3T3Poo06hK+cg23WQUzZwEc3BBIuusc5kQGztmAYmmK8H
REQp5p1WDyp8LnkaYoRIwAqOTxJ7rlTUz/o12+Oy7VT6POn9wRu0xnwpUCfUkDeB
R4U0cBfm29COO0asoldEA7dKU37syHNnZjzwgw8rR7gKpwVOoO0ldnqoIZ+PTkch
zIbzvQIjKUVxTnr42mdxJWB1PO7EaJf6eo1+HeylfCjPRmXlIzJLpRnRC/PI3IWE
NJG8sKgdlIIogL2rZQxRuFzXFBTlcJw1OARW6cid8to=
=tCF2
-----END PGP MESSAGE----- 
```

**Comment by CoNETProject** [comment]
Fixed.
