### ISSUE TITLE
建议在项目首页 README.md 这里加上使用说明

### ISSUE THREAD

**Issue by Just2co** [QTGate/QTGate-Desktop-Client#3]
如题：请附上简易使用说明，怎么配置，怎么优化，怎么在VPS搭建自己的QTGate服务，谢谢！

**Comment by CoNETProject** [comment]
好主意，感謝您的建議。自己搭建OPN技術的服務器--客戶端，請看個項目的網頁：

- 代理端和客戶端使用IMAP協議混淆技術的無IP地址通訊@OPN項目[https://github.com/QTGate/atOPN](https://github.com/QTGate/atOPN)

- 代理端和客戶端使用HTTP協議混淆技術的iOPN項目[https://github.com/QTGate/iOPN](https://github.com/QTGate/iOPN)
