### ISSUE TITLE
给的节点连ping 都ping 不通。还不让换，肯定连不上。

### ISSUE THREAD

**Issue by ningblue** [QTGate/QTGate-Desktop-Client#4]
怎么可以更换节点呢？？？？？？

**Comment by CoNETProject** [comment]
您可以選擇一個代理服務區後，點擊連結後您會連結到一個節點或幾個節點。而我們的節點是自動切換的。每二個小時您的節點IP會換成另外的節點。如果您希望換代理服務區，您可以點擊**切斷連結**，再重新選擇代理服務區，來進行新的連結。Q梯不提供**手動換節點**。我們的節點**不響應Ping**，也不會回應對節點的任何其他嘗試，而如果有不被許可的嘗試動作，該**IP會被自動屏蔽**。
**選擇代理服務區**
<img width="850" alt="iopn1" src="https://user-images.githubusercontent.com/19976150/34886922-8749d518-f779-11e7-9fa2-089ba63419ca.png">
**連結成功**
![26220358_1655801451108977_7433956157094507444_o](https://user-images.githubusercontent.com/19976150/34886898-79a23608-f779-11e7-8971-656a76ae1212.jpg)

**Comment by ningblue** [comment]
我也是这么做的 ，但就是仍然无法访问  安卓系统  windows 火狐 我都尝试了，还是打不开网页

**Comment by CoNETProject** [comment]
您可以觀看以下這個
[【視頻教程】](https://twitter.com/PeterQTGate/status/951995414676307969)

**Comment by CoNETProject** [comment]
火狐瀏覽器代理設置指南

https://twitter.com/PeterQTGate/status/952042889265098752

**Comment by ningblue** [comment]
非常感谢╰(*´︶`*)╯我再尝试一下

**Comment by CoNETProject** [comment]
從下載安裝，設置到使用的視頻全教程。
https://plus.google.com/106646324846752814464/posts/f1CXXMevnV8

**Comment by CoNETProject** [comment]
我們服務器從昨天開始有一個程序錯誤，導致全部客戶無法使用代理服務器。如今已經被修復。

**Comment by wwq133585** [comment]
每条延迟都很高

**Comment by CoNETProject** [comment]
您試一下youtube的4K視頻，我們有些客戶最快可以達到20MB，不光看延遲您還可以看一下速度。我們近期還會推出法國巴黎，日本東京，阿爾蘭和澳洲悉尼代理區，您可以有多個服務區的選擇。
