### ISSUE TITLE
连接上了，但断开时有问题

### ISSUE THREAD

**Issue by Alobe007** [QTGate/QTGate-Desktop-Client#5]
连接上以后，使用流畅。实测Youtube的1080没问题。

但要断开连接时显示：正在切断中，就没反应了。

此时仍可上推特，说明连接实际并未中断。

另外，建议在连接页面上，增加对已连接设备的监控功能，这样能知道当前有几个连接中的设备，以免误断连接影响使用。

**Comment by Alobe007** [comment]
关了QTgate，再杀了进程重新起动一次，这回可以断开连接了。

貌似是QTgate进程的问题。因为关了QTgate后，任务管理器中还有一个QTGate.exe的进程，要手动杀掉。

**Comment by CoNETProject** [comment]
感謝您的報告。不能夠斷開我們也獲得了其他用戶的反映。看來這是我們服務器的問題。我們技術團隊會針對這個問題進行修復。

對連結設備的跟蹤是非常好的好注意，我們會研究並可能在新版本中推出這項功能。
