### ISSUE TITLE
能支持一下 protonmail 吗？

### ISSUE THREAD

**Issue by ghost** [QTGate/QTGate-Desktop-Client#6]
临时邮箱，可以把 protonmail 支持加入吗？

**Comment by CoNETProject** [comment]
我們已經對protonmail做了評估，但是非常遺憾的是，它不支持IMAP通訊。我們的技術需要使用IMAP來進行客戶端網絡的路由功能。

https://protonmail.com/support/knowledge-base/imap-smtp-and-pop3-setup/
