### ISSUE TITLE
客户端代理怎么使用?

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [QTGate/QTGate-Desktop-Client#7]
![2018-01-22_144749](https://user-images.githubusercontent.com/12248166/35208438-6439425e-ff83-11e7-975f-3e1ee51ce8de.jpg)

我已经正确的连上外面服务器，但是浏览器并不能上google。

我电脑的ip是192.168.1.100，我分别把浏览器的代理设成192.168.1.100  3001 socks5 和127.0.0.1 3001 socks5都不能上网。

在cmd中telnet 192.168.1.100 3001  telnet 127.0.0.1 3002都不能，说明本地socks服务未启动。

怎么解决?   @QTGate 

----------------------------------------------

问题已经解决，是因为与服务器的连接有问题，本地socks5没有监听，换了一个服务器解决。谢谢!

.

**Comment by CoNETProject** [comment]
是的我們今天日本代理區和澳洲代理區由於人數爆滿，而我們的供應商沒有給我們更多的服務器可使用，以至於很多人連結以上二個區域，沒有資源不能夠產生虛擬機，搭建代理服務器而使得等待時間超時。對不起。
