### ISSUE TITLE
请出一个windows xp版本

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [QTGate/QTGate-Desktop-Client#8]
一方面有很大的群体还在使用xp ，同时xp比较适合在虚拟机中跑。

我试过了32位的版本，在xp中无法安装。请提供一个xp 32位的版本。

谢谢！

.

**Comment by CoNETProject** [comment]
感謝您的建議，因為我們的軟件是運行在NodeJS環境下，編譯可執行文件是通過第三方稱為[Electronjs](https://electronjs.org/docs)的項目產生各個系統版本，目前Electronjs不支持生成WIndowsXP版本可執行文件。我們今後會考慮推出一個NodeJS環境的NPM項目，客戶需安裝NodeJS，並通過NPM的install來安裝。

**Comment by piiiiiiiiiiiiiii** [comment]
谢楼上
