### ISSUE TITLE
连接问题

### ISSUE THREAD

**Issue by shown1985** [QTGate/QTGate-Desktop-Client#9]
连接QTGate时发生错误，请修改IMAP账号设定
使用Zoho，服务器通讯评价3颗星
报错信息：
switch data.qtGateConnection goto default! data.qtGateConnection = [3]

**Comment by CoNETProject** [comment]
這個問題我們已經記錄，在新版本中會的到解決。

**Comment by shown1985** [comment]
请问新版本何时上线？上线前就只能等待了吗

**Comment by CoNETProject** [comment]
您使用Zoho郵箱應該是沒有問題。當連結QTGate系統發生錯誤時，您可以按右下角QTGate圖標，點擊鼠標右鍵在菜單中選擇退出QTGate，然後重新打開QTGate客戶端，一般問題可以得到解決。而switch data.qtGateConnection goto default! data.qtGateConnection = [3] 這個錯誤發生，不影響QTGate的使用。

**Comment by shown1985** [comment]
1.退出重新进入还是这个问题，无法解决
2.影响使用“连接QTGate时发生错误，请修改IMAP账号设定”
已向QTGate系统发送连接请求Email。由于是首次连接QTGate系统，系统需要几分钟时间来完成与您的对接，请耐心等待。
这步就一直过不去了

**Comment by CoNETProject** [comment]
在您的系統盤有QTGate的log文件：c:\users\您的用戶名\ .QTGate\imap.log，您打開看看在IMAP連結到您的Zoho郵箱後，當和QTGate系統連結成功後雙方會發送ping和pong信息，您看看有沒有收到QTGate發送的ping，或者您的客戶端發送ping後，有沒有收到QTGate系統回送的pong。

**Comment by shown1985** [comment]
imap.log
Tue, 06 Feb 2018 06:19:22 GMT: 【2018-02-06T06:19:22.772Z】<= 【c5a32d4b-0960-42e5-828e-97258f4f7dd4 A7 OK Success】
Tue, 06 Feb 2018 06:19:22 GMT: 【2018-02-06T06:19:22.772Z】=> 【A8 UID STORE 1 FLAGS.SILENT (\Deleted)】
Tue, 06 Feb 2018 06:19:24 GMT: 【2018-02-06T06:19:24.679Z】<= 【c5a32d4b-0960-42e5-828e-97258f4f7dd4 * 1 FETCH (FLAGS (\Deleted) MODSEQ (1000000000000000003) UID 1)】
Tue, 06 Feb 2018 06:19:24 GMT: 【2018-02-06T06:19:24.680Z】<= 【c5a32d4b-0960-42e5-828e-97258f4f7dd4 * 1 EXPUNGE】
Tue, 06 Feb 2018 06:19:24 GMT: 【2018-02-06T06:19:24.680Z】<= 【c5a32d4b-0960-42e5-828e-97258f4f7dd4 A8 OK Success】
Tue, 06 Feb 2018 06:19:24 GMT: 【2018-02-06T06:19:24.680Z】=> 【A9 EXPUNGE】
Tue, 06 Feb 2018 06:19:24 GMT: 【2018-02-06T06:19:24.882Z】<= 【c5a32d4b-0960-42e5-828e-97258f4f7dd4 A9 OK Success】
Tue, 06 Feb 2018 06:19:24 GMT: 【2018-02-06T06:19:24.882Z】=> 【A10 LOGOUT】
Tue, 06 Feb 2018 06:19:25 GMT: 【2018-02-06T06:19:25.083Z】<= 【c5a32d4b-0960-42e5-828e-97258f4f7dd4 * BYE IMAP4rev1 Server logging out】
Tue, 06 Feb 2018 06:19:25 GMT: 【2018-02-06T06:19:25.083Z】<= 【c5a32d4b-0960-42e5-828e-97258f4f7dd4 A10 OK Success】
Tue, 06 Feb 2018 06:19:25 GMT: jj.once ( 'end' ) listenFolder[c5a32d4b-0960-42e5-828e-97258f4f7dd4] writeFolder [null]
Tue, 06 Feb 2018 06:19:25 GMT: rImap.once ( 'end' ) [err = undefine]
Tue, 06 Feb 2018 06:19:26 GMT: doing peer account [xxxxxxx@zoho.com] listen with[adb7bb2a-e4b8-401d-9a3d-c438c2703764], write with [c8295ade-a1d7-4432-9c4f-c1a83cbfa902] 
Tue, 06 Feb 2018 06:19:26 GMT: newReadImap!
Tue, 06 Feb 2018 06:19:32 GMT: qtGateImap got process uncaught Exception [undefined]

**Comment by shown1985** [comment]
systemError.log

Tue, 06 Feb 2018 06:19:32 GMT: ImapConnect exit err > 0 【6】
Tue, 06 Feb 2018 06:19:36 GMT: transporter.sendMail success!
Tue, 06 Feb 2018 06:19:36 GMT: doing makeTimeOutEvent
Tue, 06 Feb 2018 06:19:36 GMT: class [ImapConnect] connect QTGate timeout! send request mail to QTGate! success
Tue, 06 Feb 2018 06:19:38 GMT: smtpVerify ERROR: err number = [10]
Tue, 06 Feb 2018 06:19:38 GMT: smtpVerify ERROR: err number = [10]
Tue, 06 Feb 2018 06:19:54 GMT: smtpVerify ERROR: err number = [10]

**Comment by CoNETProject** [comment]
QTGate在安裝和使用的過程中，請關閉VPN和代理服務，QTGate使用的前提是不須翻牆。我看見您有一條非預期的錯誤發生，IMAP通訊被終止，這樣的問題大部分發生在使用VPN連結的狀態下：
```
Tue, 06 Feb 2018 06:19:32 GMT: qtGateImap got process uncaught Exception [undefined]
```

**Comment by shown1985** [comment]
都关闭了，实在不清楚还有什么了。。
Tue, 13 Feb 2018 02:03:35 GMT: qtGateImap got process uncaught Exception [undefined]

**Comment by shown1985** [comment]
Tue, 13 Feb 2018 02:03:29 GMT: doSendConnectMail
Tue, 13 Feb 2018 02:03:29 GMT: doReady
Tue, 13 Feb 2018 02:03:29 GMT: Class ImapConnect start up!
Tue, 13 Feb 2018 02:03:35 GMT: ImapConnect exit err > 0 【6】
Tue, 13 Feb 2018 02:03:39 GMT: transporter.sendMail success!
Tue, 13 Feb 2018 02:03:39 GMT: doing makeTimeOutEvent
Tue, 13 Feb 2018 02:03:39 GMT: class [ImapConnect] connect QTGate timeout! send request mail to QTGate! success
Tue, 13 Feb 2018 02:03:41 GMT: smtpVerify ERROR: err number = [10]
Tue, 13 Feb 2018 02:03:41 GMT: smtpVerify ERROR: err number = [10]
Tue, 13 Feb 2018 02:03:58 GMT: smtpVerify ERROR: err number = [10]

**Comment by CoNETProject** [comment]
```
smtpVerify ERROR: err number = [10]
```
這個錯誤看來是您的IMAP帳號APP密碼有誤。
您可以選用我們提供的IMAP帳號試一下：
[iCloud臨時帳戶](https://github.com/QTGate/QTGate-Desktop-Client/wiki/iCloud%E8%87%A8%E6%99%82%E5%B8%B3%E6%88%B6)

**Comment by shown1985** [comment]
你们提供的临时账户是没问题的可以连接，我再试试自己zoho的吧。。

**Comment by shown1985** [comment]
问题解决了，解决方式：
删除了%userprofile%下.qtgate下的config.json，然后重新打开配置了一次就好了。原因未知

**Comment by CoNETProject** [comment]
感謝您的信息，我會讓我們技術團隊檢查這一個問題。
